### ISSUE TITLE
Source files that are part of a dynamic import don't get minified

### ISSUE THREAD

**Issue by peter-f-kruger** [zodern/minify-js-sourcemaps#24]
Well, the title already explains the problem at hand, there isn't more to elaborate.  These source files seemingly don't go through any processing at all, e.g. even the comments are left as-is.

**Comment by zodern** [comment]
I am unable to reproduce. Are you checking the content on disk, the response of the HTTP requests to get dynamic imports, or the source in the debugger/source tab of the browser's dev tools? If it is the source shown in the dev tools, it might be because it is using source maps. Adding the `zodern:hide-production-sourcemaps` would prevent them from being used in production.

**Comment by peter-f-kruger** [comment]
I'm seeing the full source in the source tab of Chrome dev tools, including comments – but only of those files which are outside of the initial bundle, and of no other.

I did not add `zodern:hide-production-sourcemaps` on purpose, for I'm trying to find a bug in production that I know occurs from time to time on certain devices but which I'm unable to reproduce on my own.

**Comment by zodern** [comment]
The source maps include the original content of the files, which the dev tools are showing you. If you disable source maps in the devtools, it will show you the minified content.

**Comment by peter-f-kruger** [comment]
Oh I wasn't aware of that, I'm sorry, it's obviously my bad.  In this case I'm wondering though why the sources of all the other files, i.e. those in the initial bundle can't be seen – except minimized.
